### ISSUE TITLE
Finite Element Format

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#110]
The CUTE paper says that the format is defined in [this book](https://www.amazon.com/Matrices-Numerical-Mathematics-Scientific-Computation/dp/0198534213), which I don't have. @dpo, do you have it?
Otherwise, I'm gonna write some trivial function calls just to increase coverage.

**Comment by dpo** [comment]
You can also find a description of that format [here](https://www.cise.ufl.edu/research/sparse/matrices/DOC/rb.pdf).

**Comment by abelsiqueira** [comment]
Thanks. Tests implemented in #115.
