### ISSUE TITLE
Manually updating the specialized function - end of the script era

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#111]
I started making updates on the specialized functions, without the scripts. Some fine-tuning is required, and the script was becoming too exception-based.

That said, if there is some big change to do, it is better to do now.

**Comment by dpo** [comment]
Is this related somehow to #42? There's very little chance the core interface will ever change again, except perhaps once in a blue moon when a new function is added to CUTEst. So I'm in favor of phasing out the script and fine-tuning the interfaces by hand.

**Comment by abelsiqueira** [comment]
Somewhat related. The first change I made manually was #107, uncovered on #42.
Glad you agree. I'm confident that NLPModels will handle most use cases.
