### ISSUE TITLE
Bug on cdimsh

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#113]
Some weird bug on `cdimsh` or on `HS10`. Possibly on general CUTEst, not sure.

```julia
using CUTEst
nlp = CUTEstModel("HS10")
hess(nlp, ones(2), y=[1.0]) # works
cdimsh()
hess(nlp, ones(2), y=[1.0]) # returns a different matrix
```

`HS10` has a linear objective function, but maybe not related.

**Comment by abelsiqueira** [comment]
Also had problems with `cshprod` on `HS10`, but this is one harder to recreate. I'm gonna remove `HS10` from the tests, at least for now.

**Comment by dpo** [comment]
I can reproduce the problem. I'll have to look if it's reproducible with Fortran.

**Comment by dpo** [comment]
I can reproduce this in Fortran. Now let's try to fix it.

**Comment by dpo** [comment]
Could you confirm that the latest CUTEst HEAD fixes it for you too?

**Comment by abelsiqueira** [comment]
I've been using https://github.com/optimizers/cutest-mirror/ to download, can you make a new release?

**Comment by abelsiqueira** [comment]
The bug was fixed, i.e., hs10 passes the consistency checks again.

I'm getting a different bug now, however.
```
sifdecoder DIXMAANJ param M=5
```
gives error on line 199. It looks like the variable `AWK` is not set.

Unfortunately I've been using an old CUTEst version, and didn't catch this sooner.

**Comment by dpo** [comment]
That's probably easy to fix. A new release will take more time because the git/svn sync is broken. It'll be a few days before I can get to it.

**Comment by dpo** [comment]
Fixed in HEAD. Note that the correct syntax is `sifdecoder -param M=5 DIXMAANJ`.

**Comment by abelsiqueira** [comment]
While returning `hs10` to the tests, I found the error on `cshprod`.
```julia
using CUTEst

nlp = CUTEstModel("HS10")

r = hprod(nlp, nlp.meta.x0, [1.0;0.0], y=[-pi])
c = 0
err = 0.0
for i = 1:100000
  nnzr, Is, s = cshprod(nlp.meta.nvar, nlp.meta.ncon, false, nlp.meta.x0,
                        [-pi], 1, Cint[1], [1.0])
  if norm(s - r) > 1e-6
    c += 1
    err += norm(s - r)
  end
end

println("$c errors, avg $(err/c)")

finalize(nlp)
```

**Comment by abelsiqueira** [comment]
The error happened on cutest-mirror 0.3 and 9a3683d (before the fix for cdimsh).

**Comment by abelsiqueira** [comment]
Closing this because there is no more specialized interface #132

**Comment by dpo** [comment]
Is the bug still present?

**Comment by abelsiqueira** [comment]
I can't reproduce it with the core interface. It was something with the specialized, but I couldn't find what.
