### ISSUE TITLE
SCURLY10: wrong starting point

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/CUTEst.jl#131]
For me on OSX with Julia 0.6, `CUTEstModel("SCURLY10")` reports a zero starting point, which is not what's indicated in the SIF file. A Fortran driver reports the correct (nonzero) starting point.

**Comment by abelsiqueira** [comment]
Reproduced on Julia. It's extremely odd, since we decode the problem from the SIF file.

**Comment by abelsiqueira** [comment]
I ran the TRON driver to print the starting point, and it's all zeros. I'm using the same CUTEst.jl installation. Do you have two installations?

**Comment by abelsiqueira** [comment]
PS. I found out that I can use `sifdecoder -o 1 SCURLY10` to see the starting point. It's still showing all zeros though.

**Comment by dpo** [comment]
I must have done something wrong yesterday. Now the C and Fortran drivers also report a zero starting point. But it's clearly nonzero in the SIF file.

**Comment by dpo** [comment]
Fixed upstream.
