### ISSUE TITLE
Strange error with `ushprod`

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#135]
Was #126.

I updated the example to check all problems with two variables or less, and many of them have errors.
However, when I change the code to not allocate the input so many times, it works normally.

The failing code is [here](https://gist.github.com/abelsiqueira/2098fd39adb32cfe46bd310acffa5f63), and I think it may be simplified.

The change to make it work is simply:
```
ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], Cdouble[1.0], nnzr, Ir, r)
ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], Cdouble[1.0], nnzr2, Ir2, r2)
```
to
```
ushprod(io_err, Cint[n], goth, x0, nnzs, Is, s, nnzr, Ir, r)
ushprod(io_err, Cint[n], goth, x0, nnzs, Is, s, nnzr2, Ir2, r2)
```
This makes me think it's something related to memory allocation. I'm not sure what, though, or how to prevent this.

**Comment by dpo** [comment]
The [Fortran source code](https://github.com/optimizers/cutest-mirror/blob/master/src/tools/ushprod.f90#L25) says that `VECTOR`, the vector with which you compute the product, should be of size `n`. That's probably an error.

**Comment by dpo** [comment]
This results in no errors at all:
```diff
diff --git a/issue126.jl b/issue126.jl
index ed23ffa..24b3de3 100644
--- a/issue126.jl
+++ b/issue126.jl
@@ -22,12 +22,14 @@ function foo()
     err_sum1 = 0.0
     err_sum2 = 0.0
 
+    vect = ones(Cdouble, n)
+
     nnzr, Ir, r = Cint[0], Array{Cint}(n), zeros(n)
-    ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], Cdouble[1.0], nnzr, Ir, r)
+    ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], vect, nnzr, Ir, r)
     CUTEst.@cutest_error
     for i = 1:N
       nnzr2, Ir2, r2 = Cint[0], Array{Cint}(n), zeros(n)
-      ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], Cdouble[1.0], nnzr2, Ir2, r2)
+      ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], vect, nnzr2, Ir2, r2)
       CUTEst.@cutest_error
       if norm(r - r2) > 1e-6
         err_count1 += 1
@@ -41,7 +43,7 @@ function foo()
 
     for i = (N+1):2N
       nnzr2, Ir2, r2 = Cint[0], Array{Cint}(n), zeros(n)
-      ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], Cdouble[1.0], nnzr2, Ir2, r2)
+      ushprod(io_err, Cint[n], goth, x0, Cint[1], Cint[1], vect, nnzr2, Ir2, r2)
       CUTEst.@cutest_error
       if norm(r - r2) > 1e-6
         err_count2 += 1
@@ -64,4 +66,4 @@ function foo()
   end
 end
 
-foo()
\ No newline at end of file
+foo()
```
The size of `VECTOR` is [consistent](https://github.com/optimizers/cutest-mirror/blob/79db52cccb6544260c849281e01414038be563bb/src/tools/cutest.f90#L2979) in the library but I wonder if it's intentional.

**Comment by abelsiqueira** [comment]
Ah, thanks. I though it would use the value of `nnz_vector`. Not a bug, so closing.

**Comment by dpo** [comment]
We should be sure our doc is clear about that.

**Comment by abelsiqueira** [comment]
For the core interface I just copied the `DESCRIPTION` in the `man`. The only further description is the function call and the types of each parameter. Should I add the disclaimer above as additional information?

**Comment by dpo** [comment]
It should say somewhere that the input and output vectors are of size `n`, otherwise, it's tempting to think that they should only contain the nonzero elements.
