### ISSUE TITLE
KOWOSBNE is "unc", but has ncon = 11?

### ISSUE THREAD

**Issue by anriseth** [JuliaSmoothOptimizers/CUTEst.jl#147]
I got "KOWOSBNE" from `CUTEst.select(contype="unc")`, however, `nlp.meta.ncon = 11`.

Is this a mistake in MASTSIF that I should report, or is there a reason for this?

**Comment by dpo** [comment]
Thanks. It looks like the classification string is erroneous. It's a feasibility problem that is intended to represent an unconstrained nonlinear least-squares problem. `KOWOSB` is a `SUR2` but `KOWOSBNE` should be a `NOR2`.

**Comment by anriseth** [comment]
Okay. Shall I report this to Nick Gould, or is this something you guys can change in mastsif yourselves?

**Comment by dpo** [comment]
I'll do it.

**Comment by dpo** [comment]
Fixed in mastsif-mirror (tag v0.4) and in the Homebrew formula. @abelsiqueira Does linux-cutest need updating?

**Comment by abelsiqueira** [comment]
Updated now. I think it's time to a new release.

**Comment by dpo** [comment]
Sounds good.
