### ISSUE TITLE
Clear decoded problems

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/CUTEst.jl#180]
We need a function to clean up `deps/files`. Mine weighs 1.9Gb...

**Comment by amontoison** [comment]
@dpo I added two functions for this issue in #401 (`clear_libsif` and `manage_libsif`).
- The first one removes all files in `deps/files`.
- The second is interactive and allows the user to remove only the files they want.
![Capture d’écran du 2024-08-28 01-19-05](https://github.com/user-attachments/assets/3acee647-fe53-4f8c-b0da-8b31f1792244)
