### ISSUE TITLE
Problems when converting to MPB

### ISSUE THREAD

**Issue by pjssilva** [JuliaSmoothOptimizers/CUTEst.jl#184]
If I try the following simple code
```julia
using CUTEst, NLPModelsJuMP, Ipopt
nlp = CUTEstModel("HS110")
model = NLPtoMPB(nlp, IpoptSolver())
```
I get an `ERROR: hess_structure not implemented`.  If I try the same but with an AlgencanSolver (from Algencan.jl), I get `ERROR: jac_structure not implemented`. 

Am I doing something wrong here?

**Comment by abelsiqueira** [comment]
Hi @pjssilva, I believe this is a version problem.

The latest `NLPModelsJuMP` was updated to work with `NLPModels` 0.8.0, but `CUTEst.jl` did not have a version limit, so it broke. I made a release for CUTEst ([0.6.0](https://github.com/JuliaLang/METADATA.jl/pull/22390)), that should fix the current problem. It should be merged in a few hours, but if you need it now, you can
```julia
pkg> add CUTEst#master
```
for the update.

Alternatively, if you just `pkg> update` your packages, CUTEst should go to version 0.5.0 which now has a version limit, downgrading a few packages along the way.

Also, you should check [`NLPModelsIPopt`](https://github.com/JuliaSmoothOptimizers/NLPModelsIpopt.jl/), to call `Ipopt` on `nlp` directly.

**Comment by pjssilva** [comment]
Thanks,

I have just updated the packages and it got back working! Now it is time for me to update Algencan.jl to MOI. Looking from Ipopt code it seems like quite a reasonable amount of work... I am afraid I won't be very fast and my package will lag behind.

**Comment by dpo** [comment]
@pjssilva How difficult would it be to call Algencan directly with an `NLPModel` (as in `NLPModelsIpopt`)? We would be happy to help develop the interface.

**Comment by pjssilva** [comment]
From what I learned doing the MPB interface I believe it should not be hard to create `NLPModel` one. I will put this in my todo list. But I will work on the MOI interface first. If I need any help I will let you know.
