### ISSUE TITLE
hess_coord touches row and col index vectors

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/CUTEst.jl#195]
Calling `cutest_csh`, `cutest_cshc` or `cutest_ush` writes into the vectors of row and column indices. That is in fact not compliant with the NLPModels API, and it causes segfaults if you call `hess_structure!` followed by `hess_coord!` with undefined row and colum index vectors (as IPOPT.jl does).

Possible solutions:
1. `hess_coord!(::CUTEstModel, args...; kwargs...)` always allocates fresh vectors `rows` and `cols` internally and throws them away after the call to `[uc]sh[c]`.
2. modify CUTEst itself to provide a subroutine that only fills in the values of the Hessian.

Solution 1 is simple but quite wasteful. I can give Solution 2 a shot and see how it goes.

Any other ideas?

**Comment by dpo** [comment]
As a side issue, if we keep the convention that `hess_coord!` and `jac_coord!` should only touch the values and not the indices, should we simplify their calling sequence so `rows` and `cols` aren't even passed?

**Comment by abelsiqueira** [comment]
There is a third way, used for [NLPModelsJuMP](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/src/mpb_model.jl#L64): storing `rows` and `cols` for the Jacobian and Hessian inside the model. There, the structure was called during construction, but it could be left to `*_structure` possibly.

Makes sense to simplify.

**Comment by dpo** [comment]
That's a good and safe idea as Solution 2 is probably not so trivial.

**Comment by dpo** [comment]
Fixed in #198.
