### ISSUE TITLE
hess_structure! not implemented

### ISSUE THREAD

**Issue by PEPERSO** [JuliaSmoothOptimizers/CUTEst.jl#197]
Hello, I think I found some error using CUTEstModel : 
```
julia> hess_structure!(HS1, [0,0,0], [0,0,0])
ERROR: hess_structure! not implemented
Stacktrace:
 [1] hess_structure!(::CUTEstModel, ::Array{Int64,1}, ::Array{Int64,1}) at /home/perselie/.julia/packages/NLPModels/GzhHY/src/NLPModels.jl:324
 [2] top-level scope at none:0

julia> jac_structure!(HS1,Int[],Int[])
ERROR: jac_structure! not implemented
Stacktrace:
 [1] jac_structure!(::CUTEstModel, ::Array{Int64,1}, ::Array{Int64,1}) at /home/perselie/.julia/packages/NLPModels/GzhHY/src/NLPModels.jl:203
 [2] top-level scope at none:0

julia>
```
It seems that the update of NLPModels to simplify code, using inplace methods is not completed for CUTEst, for hess_structure! and jac_structure

**Comment by dpo** [comment]
It's implemented: https://github.com/JuliaSmoothOptimizers/CUTEst.jl/commit/c7135e403699c769afaf4fe9bf71adeaee772378

You'll need to update CUTEst.jl#master but be careful that you will get an error if you run a CUTEst problem through IPOPT. The fix is coming.

**Comment by abelsiqueira** [comment]
I'll release a new CUTEst version today.

**Comment by abelsiqueira** [comment]
https://github.com/JuliaRegistries/General/pull/2027

**Comment by dpo** [comment]
Better hold off for a bit until I fix the hess_structure! stuff.

**Comment by dpo** [comment]
@PEPERSO see #198.
