### ISSUE TITLE
ERROR: Unable to automatically install 'sifcollection' from '/home/user/.julia/packages/CUTEst/h73Ae/Artifacts.toml'

### ISSUE THREAD

**Issue by tnnguyen103** [JuliaSmoothOptimizers/CUTEst.jl#236]
I downloaded and installed the latest version of julia (v1.5.1) for Ubuntu 18.04. When I add package CUTEst.jl, I received the error below

(@v1.5) pkg> add CUTEst.jl
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Downloading artifact: sifcollection
-=O=-                                      #     #     #    #                 
Downloading artifact: sifcollection
######################################################################## 100.0%
ERROR: Unable to automatically install 'sifcollection' from '/home/user/.julia/packages/CUTEst/h73Ae/Artifacts.toml'

Could you tell me the way to solve this matter, please? Thank you.

**Comment by abelsiqueira** [comment]
I haven't had luck recreating the problem, could you try `pkg> build CUTEst` (or removing and building again) to see if it works? There is a chance that it was a connection problem with `bitbucket`.

**Comment by dpo** [comment]
@tnnguyen103 Were you able to resolve this issue?

**Comment by tnnguyen103** [comment]
> @tnnguyen103 Were you able to resolve this issue?

Yes. It's done.
Thank @abelsiqueira for your response!

**Comment by abelsiqueira** [comment]
Great news.
