### ISSUE TITLE
helper_functions   not found

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/CUTEst.jl#238]
In the documentation, https://juliasmoothoptimizers.github.io/CUTEst.jl/latest/, the error is displayed in the usage subsection:

`/home/travis/.julia/artifacts/8e16decd1d19cfe878c0910fdcfd4cb5437df3ef/bin/sifdecoder: line 68: /home/travis/.julia/artifacts/8e16decd1d19cfe878c0910fdcfd4cb5437df3ef/libexec/ARCHDefs-2.0.3x/bin/helper_functions: No such file or directory`

I get the same error in my fresh installation.

**Comment by dpo** [comment]
Thanks. I think I have to fix that in the JLL.
