### ISSUE TITLE
Issue with -lSystem

### ISSUE THREAD

**Issue by senna1128** [JuliaSmoothOptimizers/CUTEst.jl#268]
Hi,

I'm trying to install CUTEst package on the Julia. I run
```
pkg> add CUTEst
using CUTEst
```
Then it seems it is installed without any error. I can use CUTEst.select() to select a subset of problems. However, when I try to open a problem and run
```
nlp = CUTEstModel("ROSENBR")
```
It cannot open the problem successfully. The error is
```
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
```
```
ERROR: failed process: Process(`gfortran -dynamiclib -undefined dynamic_lookup -o libROSENBR.dylib ELFUN.o EXTER.o GROUP.o RANGE.o -Wl,-rpath /Users/senna/.julia/artifacts/a5c5506e4bfa601362b9aeb09bb775994e3e65c4/libexec/CUTEst-2.0.3/objects/mac64.osx.gfo/double /Users/senna/.julia/artifacts/a5c5506e4bfa601362b9aeb09bb775994e3e65c4/libexec/CUTEst-2.0.3/objects/mac64.osx.gfo/double/libcutest_double.dylib`, ProcessExited(1)) [1]
```

I'm using Julia within JuliaPro 1.5.4-1, and my mac system is macOS BigSur 11.3.1. How to fix this issue? It seems the error relates to gfortran?

Thanks very much.

**Comment by dpo** [comment]
Thanks for the report. I haven't tested Big Sur. Our CI runs on Catalina. It's possible that something changed with the system libraries. I'll look into it.

**Comment by senna1128** [comment]
> Thanks for the report. I haven't tested Big Sur. Our CI runs on Catalina. It's possible that something changed with the system libraries. I'll look into it.

Thanks. Look forward to the resolution.

**Comment by senna1128** [comment]
Hi,

My problem is resolved and we can close the issue.

Although I did not solve the -lSystem issue. But now I can decode the problem. Just for someone who may encounter the same issue, my resolution is that 
1, I upgrade to BigSur 11.4.
2, I reinstall a higher version of gfortran via [this website](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/11.1-bigsur-intel). 
3, I switch the command line tool by
```
sudo xcode-select --switch /Library/Developer/CommandLineTools
```
4, I reopen the Julia and rerun
``` 
using CUTEst
nlp = CUTEstModel("ROSENBR")
```
It works well now, though I'm still not sure how to solve -lSystem issue.

Thanks.
