### ISSUE TITLE
`jac_coord!` memory allocation

### ISSUE THREAD

**Issue by sshin23** [JuliaSmoothOptimizers/CUTEst.jl#270]
The current implementation of `jac_coord!` internally creates `c = Vector{Float64}(undef, nlp.meta.ncon)`, which allocates memory. I was wondering if we can create a workspace array in `CUTEstModel` and reuse it whenever `jac_coord!` is called to avoid this allocation.

**Comment by dpo** [comment]
That sounds like a good idea provided it's documented properly.

**Comment by dpo** [comment]
fixed in #271
