### ISSUE TITLE
Use `increment!` and `decrement!` functions

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/CUTEst.jl#292]
instead of doing this https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/7ea04f48b9d972fb8ce37e160358a0d103186474/src/julia_interface.jl#L43

use the `increment!` function like here
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/d4c48d2fd7d599aee83b97624d3299b3fcd98c1f/src/nlp.jl#L537

The function is defined here: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/main/src/nlp/counters.jl#L59

**Comment by Jay-sanjay** [comment]
@tmigot  sir I have raised a PR for it, please do review it .

**Comment by abelsiqueira** [comment]
@Jay-sanjay, I've updated the issue definition with more information

**Comment by Jay-sanjay** [comment]
Thank you sir , I will start to work on it.
