### ISSUE TITLE
Mislcassified problems

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/CUTEst.jl#301]
I encountered the following error
```
"S308NE" in CUTEst.select(contype = "unc", only_free_var = true)
```
while
```
nlp = CUTEstModel("S308NE")
nlp.meta.ncon == 3
```

**Comment by dpo** [comment]
Please report upstream: https://bitbucket.org/optrove/sif

**Comment by nimgould** [comment]
Yes, sorry, this was a misclassification. Now fixed (it is a nonlinear system)

**Comment by tmigot** [comment]
Thanks! I will post directly to bitbucket if I find more

**Comment by nimgould** [comment]
Super, please let us know
