### ISSUE TITLE
KeyError: key "MASTSIF" not found

### ISSUE THREAD

**Issue by FengYiLiao** [JuliaSmoothOptimizers/CUTEst.jl#311]
After installing CUTEst, the command "nlp = CUTEstModel("BYRDSPHR");" shows the error (KeyError: key "MASTSIF" not found). 
I am not able to solve this issue.
I was wondering if there is any step I am missing.
Thanks.

**Comment by abelsiqueira** [comment]
Hi @FengYiLiao, can you run `set_mastsif()` and try again and let us know if it works?

**Comment by FengYiLiao** [comment]
Thank you for the prompt reply! 
The "MASTSIF" issue is solved, but another error pops out (UndefVarError: `sifdecoder` not defined)

**Comment by abelsiqueira** [comment]
Can you share more information about your system, Julia version, and other messages during installation.
Can you try `pkg> build CUTEst` and try again?
Can you try `pkg> remove CUTEst` and then `pkg> add CUTEst`, and then try again?

**Comment by FengYiLiao** [comment]
Thanks.
I tried to build CUTEst or add CUTEst again, but they do not seem to work. 

**Below is my system:**
Edition	Windows 10 Education
Version	22H2

Julia version: 1.9.2

Messages during installation:
(@v1.9) pkg> add CUTEst
   Resolving package versions...
    Updating `C:\Users\SOC-LAB\.julia\environments\v1.9\Project.toml`
  [1b53aba6] + CUTEst v0.13.2
    Updating `C:\Users\SOC-LAB\.julia\environments\v1.9\Manifest.toml`
  [1b53aba6] + CUTEst v0.13.2


**Below is the error for "sifdecoder":**

julia> nlp = CUTEstModel("BYRDSPHR");
ERROR: UndefVarError: `sifdecoder` not defined
Stacktrace:
 [1] getproperty
   @ .\Base.jl:31 [inlined]
 [2] (::CUTEst.var"#23#26"{Bool, String, String, Tuple{}, String, String, String})()
   @ CUTEst C:\Users\SOC-LAB\.julia\packages\CUTEst\FWOg3\src\CUTEst.jl:193
 [3] cd(f::CUTEst.var"#23#26"{Bool, String, String, Tuple{}, String, String, String}, dir::String)
   @ Base.Filesystem .\file.jl:101
 [4] sifdecoder(::String; verbose::Bool, outsdif::String, automat::String)
   @ CUTEst C:\Users\SOC-LAB\.julia\packages\CUTEst\FWOg3\src\CUTEst.jl:177
 [5] (::CUTEst.var"#30#31"{Bool, Bool, String, Tuple{}, Vector{Int32}, String, String})()
   @ CUTEst C:\Users\SOC-LAB\.julia\packages\CUTEst\FWOg3\src\CUTEst.jl:260
 [6] cd(f::CUTEst.var"#30#31"{Bool, Bool, String, Tuple{}, Vector{Int32}, String, String}, dir::String)
   @ Base.Filesystem .\file.jl:101
 [7] CUTEstModel(::String; decode::Bool, verbose::Bool, efirst::Bool, lfirst::Bool, lvfirst::Bool)
   @ CUTEst C:\Users\SOC-LAB\.julia\packages\CUTEst\FWOg3\src\CUTEst.jl:253
 [8] CUTEstModel(::String)
   @ CUTEst C:\Users\SOC-LAB\.julia\packages\CUTEst\FWOg3\src\CUTEst.jl:230
 [9] top-level scope
   @ REPL[15]:1

**Comment by abelsiqueira** [comment]
On WIndows, you have to use WSL, check https://jso.dev/CUTEst.jl/latest/, section **Installing**. Can you try that?

**Comment by FengYiLiao** [comment]
It is working now.
Thanks!

**Comment by abelsiqueira** [comment]
Great! Happy usage.
