### ISSUE TITLE
How to specify the size of the test problem?

### ISSUE THREAD

**Issue by Xiaoyi-Qu** [JuliaSmoothOptimizers/CUTEst.jl#312]
I'm wondering how to set the problem dimension for some of the CUTEst problems. For instance, test problem CHAIN has the following options:
```
Parameters available for problem CHAIN:
NH = 50 (int) 
NH = 100 (int) 
NH = 200 (int) 
NH = 400 (int) [default]
End of parameters for problem CHAIN
```
I have access to the default option by calling `nlp = CUTEstModel("CHAIN")`. For the time being, I can access to the other options by modifying the CHAIN.sif file. My question is if there is a smarter way to work around this.

**Comment by abelsiqueira** [comment]
Hi @Xiaoyi-Qu, thanks for creating the issue. This is not well documented, but you can use
```julia
CUTEstModel("CHAIN", "-param", "NH=50")
```
to change parameters.
I will improve the documentation a bit on this.

**Comment by Xiaoyi-Qu** [comment]
Thank you very much!
