### ISSUE TITLE
NLPModels computes gradient with elements out of order

### ISSUE THREAD

**Issue by MaiconMares** [JuliaSmoothOptimizers/CUTEst.jl#316]
In some non linear problems the `grad()` function is computing gradient correctly but returning partial derivatives out of order. For example in the HS27 problem the correct result should be [16.02,-4.0,0.0], but it is returning [0.0,-4.0,16.02]. I don't understand why this behaviour is happening.

**Comment by abelsiqueira** [comment]
Hi @MaiconMares, what order were you expecting? The paper's or wrt other packages? Maybe it is related to the setup options that we use to read the cutest file.

**Comment by MaiconMares** [comment]
> Hi @MaiconMares, what order were you expecting? The paper's or wrt other packages? Maybe it is related to the setup options that we use to read the cutest file.

Hi @abelsiqueira the correct order should be [16.02,-4.0,0.0]. How can I change the way CUTEst Julia package reads .SIF files?

**Comment by abelsiqueira** [comment]
https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/9467c8c12183bf0af42cd2ac704f9a4f28795726/src/CUTEst.jl#L264
See above and check the docs of the function.

**Comment by tmigot** [comment]
Hey @MaiconMares , what is reference you use to state what is the ''correct'' formulation?
Or is an error on the derivative computation in cutest?

**Comment by MaiconMares** [comment]
> Hi @MaiconMares, what order were you expecting? The paper's or wrt other packages? Maybe it is related to the setup options that we use to read the cutest file.

Thank you @abelsiqueira, it was the problem. `lfirst` and `lvfirst` args passed to `CUTEstModel` function was leading CUTEst to compute gradients and constraints doing partial derivatives over non-linear variables first! The solution:
```ruby
CUTEstModel("HS8",lfirst=false,lvfirst=false)
```
