### ISSUE TITLE
Make the package loadable in Windows even though it is not usable

### ISSUE THREAD

**Issue by emmt** [JuliaSmoothOptimizers/CUTEst.jl#323]
@amontoison 

The `CUTEst.jl` package cannot be loaded on Windows and on any 32-bit architectures. I guess this is because the corresponding DLLs are not provided by `CUTEst_jll.jl` (see [here](https://docs.juliahub.com/General/CUTEst_jll/stable/)). If  `CUTEst.jl` could be loaded by `using CUTEst` for any machine, even though not usable, it would make possible for other packages to (weakly) depend on `CUTEst.jl` and simply avoid using its methods if 

```julia
Sys.isunix() && Sys.WORD_SIZE ≥ 64
```

does not hold. There can even be a method provided by  `CUTEst.jl` like:

```julia
"""
    CUTEst.is_supported()

yields whether `CUTEst` is fully supported by the machine of the caller.

"""
is_supported() = Sys.isunix() && Sys.WORD_SIZE ≥ 64
```

to check this.

This would also help to investigate and solve [this issue in `PRIMA.jl`](https://github.com/libprima/PRIMA.jl/issues/19).

**Comment by amontoison** [comment]
@emmt 
I worked on a new version of CUTEst (2.1.0).
We can compile a shared library on all platform now, the library is not anymore "incomplete".
I need to verify a few things before that I generate a new `CUTEst_jll.jl` but it should be quite soon.

**Comment by amontoison** [comment]
Sorry for the delay @emmt, CUTEst.jl will be loadable on Windows with the release `0.13.3`.
