### ISSUE TITLE
Full compatibility with AbstractModel

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#55]
After #53

**Comment by dpo** [comment]
Note that the `NLPModelMeta` type is now defined inside of NLPModels; there's no need to grab it from MathProgBase.

**Comment by dpo** [comment]
What's missing here?

**Comment by abelsiqueira** [comment]
[Consistency check on NLPModels](https://github.com/JuliaOptimizers/NLPModels.jl/issues/5). You're implementing most needed things, but I can't check yet because of the genrose.mod

**Comment by dpo** [comment]
In what size do you need genrose?

**Comment by abelsiqueira** [comment]
500, same size as CUTEst default.

**Comment by abelsiqueira** [comment]
I'm gonna have to change 1e20 to Inf for compatibility.

**Comment by abelsiqueira** [comment]
Also, hess and hprod use keyword y, while CUTEst is using positional, that is,
`hess(nlp, x, y)` vs `hess(nlp, x, y=y)`.
Options:
  - Change CUTEst
  - Add keyword, but leave existing one
  - Change all

I'm going with the first for now.

**Comment by dpo** [comment]
Yes I noticed that too. The first is best in my opinion too.

**Comment by abelsiqueira** [comment]
Done
