### ISSUE TITLE
Segfaults [ON HOLD]

### ISSUE THREAD

**Issue by pkofod** [JuliaSmoothOptimizers/CUTEst.jl#64]
Edit: On hold... So apparently `Pkg.update` is really giving me a hard time today. JuMP is suddenly version 0.11.3, and the segfaults happened because it took me back to master from develop. Now I can't run anything... I'll close if I resolve it.

So, I updated my CUTEst.jl and now I am getting segfaults

```
using CUTEst, Optim
for i = 1:100
    nlp=CUTEstModel("CLIFF")
    optimize(x->obj(nlp,x), nlp.meta.x0)
    cutest_finalize(nlp)
end
```

```
signal (11): Segmentation fault
cutest_uofg_threadsafe_ at /home/pkm/.linuxbrew/lib/libcutest_double.so (unknown line)
cutest_uofg_ at /home/pkm/.linuxbrew/lib/libcutest_double.so (unknown line)
anonymous at no file:0
unknown function (ip: 0x7fc998d609db)
jl_toplevel_eval_in at /home/pkm/julia/usr/bin/../lib/libjulia.so (unknown line)
objgrad at /home/pkm/.julia/v0.4/CUTEst/src/julia_interface.jl:37
obj at /home/pkm/.julia/v0.4/CUTEst/src/julia_interface.jl:45
jl_apply_generic at /home/pkm/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at none:3
optimize at /home/pkm/.julia/v0.4/Optim/src/nelder_mead.jl:216
jlcall_optimize_21747 at  (unknown line)
jl_apply_generic at /home/pkm/julia/usr/bin/../lib/libjulia.so (unknown line)
optimize at /home/pkm/.julia/v0.4/Optim/src/optimize.jl:25
anonymous at none:3
unknown function (ip: 0x7fc998d609db)
jl_toplevel_eval_in at /home/pkm/julia/usr/bin/../lib/libjulia.so (unknown line)
eval_user_input at REPL.jl:62
jlcall_eval_user_input_21445 at  (unknown line)
jl_apply_generic at /home/pkm/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at REPL.jl:92
unknown function (ip: 0x7fc998d51f53)
unknown function (ip: (nil))
Segmentation fault (core dumped)

```

Can you replicate this?

**Comment by abelsiqueira** [comment]
Hey @pkofod, we're in the middle of some big changes, and Pkg.update probably won't get them. I think that
````
Pkg.clone("https://github.com/JuliaSmoothOptimizers/NLPModels.jl")
Pkg.checkout("NLPModels", "develop")
Pkg.clone("https://github.com/JuliaSmoothOptimizers/CUTEst.jl")
Pkg.checkout("CUTEst", "develop")
Pkg.build("CUTEst")
````
can give you a working version, after you fix the dependence problems.

By the way, I've had the same problems with MathProgBase and JuMP before. I think that Pkg.free("MathProgBase") or something in this line fixed it for me.

**Comment by pkofod** [comment]
All seems to be working now. I ended up simple deleting all package files and started from scratch, adding one package at a time. So I should clone from JuliaSmoothOptimizers from now on?

**Comment by abelsiqueira** [comment]
Yes, we just changed the name. Will release soon(ish) too.

**Comment by pkofod** [comment]
Good to see this getting attention, I really think it's going to improve our understanding of the performance of Optim.
