### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/CUTEst.jl#68]
- [x] document all methods (some docstrings from `NLPModels` could perhaps be reused here?)
  - [x] NLPModels #75 
  - [x] specialized and core #76 
- [x] write a simple tutorial

**Comment by abelsiqueira** [comment]
Tutorial will be released soon

**Comment by dpo** [comment]
Is anything still missing here?

**Comment by abelsiqueira** [comment]
No, this is done for now.
