### ISSUE TITLE
Consider MetaPkg

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#84]
[MetaPkg](https://github.com/tbreloff/MetaPkg.jl) by tbreloff.
- Is it better than what we do?
- Is it completely enough to do what we do?
- Will community adopt it?

**Comment by dpo** [comment]
Seems like a more sophisticated version of what I quickly put together. It's worth a good try!

**Comment by abelsiqueira** [comment]
Somewhat related: https://github.com/JuliaLang/METADATA.jl/issues/6761

**Comment by abelsiqueira** [comment]
It seems that development has slowed down, possibly due to Pkg3.
