### ISSUE TITLE
Simplify?

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#89]
CUTEst has too many methods. Besides the core functions and the NLPModels variant, there is also the specialized interface, which I'm not completely sure how useful it is.

For each core function, the specialized interface has between one and six versions of that function.

- One returning all outputs
- One inplace version when there are arrays in the output
- One additional inplace version when there are integer arrays in the output (`Int`->`Cint`)
- If some inputs can be replaced by `nlp`, then another version for each of the previous ones.

See [ugh](https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/develop/src/specialized_interface.jl#L1065), for an example using all six.

Do we need all these versions?

I think a leaner solution would be creating only two interfaces

- Both using `nlp`
- One returning all outputs
- One inplace

**Comment by dpo** [comment]
I agree we need to trim this down. I think only the Julia interface should use `NLPModel`s, and it should build on the core interface. That would also help coverage a lot. I propose to only keep inplace versions of the core interface functions. That should make the code much more manageable. What do you think?

**Comment by abelsiqueira** [comment]
The core interface is already only inplace, though we don't use `!` on the names.

Not using `nlp` on both is a valid option too. Let me work on this a little.

**Comment by abelsiqueira** [comment]
On the `Cint` front. The core interface only accepts `Array{Cint}` because of `ccall`. The specialized interface has two options:
- Only accept `Array{Cint}`. The user has to comply to make it work.
- Only accept `Array{Int}`. We would have to make a conversion using a temporary vector of `Cint`s.

**Comment by dpo** [comment]
Let's only use `Cint` and have the thinnest interface possible. I doubt anyone who wants to use Julia will want to call the core interface directly.

**Comment by abelsiqueira** [comment]
Closed by #90
