### ISSUE TITLE
`finalizer`

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/CUTEst.jl#91]
Add a `finalizer` for CUTEst.

Related: https://github.com/JuliaSmoothOptimizers/Optimize.jl/issues/32

**Comment by dpo** [comment]
I'm not sure how to do that when the constructor is defined outside the type.

**Comment by abelsiqueira** [comment]
Looks like it's easy add this so that `finalize(nlp)` calls `cutest_finalize`. But I don't see any other "advantage". I expected this to be called if I left the scope of a function where the `CUTEstModel` was created.

**Comment by dpo** [comment]
It's only called when the garbage collector finally kicks in, which is a bit unpredictable unless you call `gc()` explicitly.

**Comment by abelsiqueira** [comment]
Closed by #92
